# Generated by Django 5.0.3 on 2024-05-23 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservationApp', '0021_alter_seats_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='isDaily',
        ),
    ]
