# Generated by Django 5.0.3 on 2024-05-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationApp', '0022_remove_bus_isdaily'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='time_taken',
            field=models.DurationField(blank=True, help_text='Time taken by the bus to complete the trip', null=True),
        ),
    ]
