# Generated by Django 5.0.3 on 2024-05-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationApp', '0023_schedule_time_taken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='time_taken',
        ),
        migrations.AddField(
            model_name='schedule',
            name='time_taken_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schedule',
            name='time_taken_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
